# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca8c4d40e1fd23103f53792c65716825fa11ef446840f698a390751fba0d47ca79a09686bd0c85dbc500ff497fb6a9d9fe4b57a24ebd972700f724ec47930698

test:
  secret_key_base: d78e8d059119063b5c1c1159a796a0764a4106a61e4d7f6bee7d11120eaf1464c71bf3d7d67c913894f7e7e20efd7509cb74245d658a3eb974f46613c76f6ff9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
